openapi: 3.0.0
info:
    title: KFZ Kennzeichen API
    version: 1.0.0
paths:
    /kfzkennzeichen/v1/unterscheidungszeichen/{id}:
        get:
            summary: Ein bestimmtes Unterscheidungszeichen abfragen
            parameters:
                - name: id
                  in: path
                  description: Unterscheidungszeichen, das gesucht werden soll, z.B. "KA" für "Karlsruhe"; Groß-/Kleinschreibung wird ignoriert
                  required: true
                  schema:
                    type: string
            responses:
                '200':
                    description: Unterscheidungszeichen gefunden
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RestErgebnis'
                '404':
                    description: Unterscheidungszeichen nicht gefunden
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RestErgebnis'
    /kfzkennzeichen/v1/unterscheidungszeichen:
        post:
            summary: Neues Unterscheidungskennzeichen anlegen
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UnterscheidungszeichenIntern'
            responses:
                '200':
                    description: Unterscheidungszeichen erfolgreich angelegt
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RestErgebnis'
                '409':
                    description: Unterscheidungszeichen existiert bereits, kann nicht angelegt werden
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RestErgebnis'
components:
    schemas:
        RestErgebnis:
          type: object
          properties:
            erfolg:
              type: boolean
            nachricht:
              type: string
            unterscheidungszeichen:
              $ref: '#/components/schemas/UnterscheidungszeichenIntern'
          required:
            - erfolg
            - nachricht
            - unterscheidungszeichen
        UnterscheidungszeichenIntern:
            type: object
            properties:
                unterscheidungszeichen:
                    type: string
                    description: Unterscheidungszeichen von KFZ-Kennzeichen, z.B. "KA" für Karlsruhe
                bedeutung:
                    type: string
                    description: Bedeutung des Unterscheidungszeichens
                kategorie:
                    type: string
                    description: Kategorie des Unterscheidungszeichens, z.B. Abkürzung Bundesland
            required:
                - unterscheidungszeichen
                - bedeutung
                - kategorie